project = "ai-deployment-bootcamp"
region = "us-east-1"
user = "username"
scriptpath = "./ml-api/startup.sh"
publickeypath = "~/.ssh/id_rsa.pub"
db_password = "supersecurepassword"
endpoint = "1513372202517397504"