project = "your-unique-project-name"
short_project_prefix = "short-prj-name"
region = "us-central1"
user = "your.user"
publickeypath = "~/.ssh/id_rsa.pub"
schemas_folder = "../../schemas"
endpoint = "3743685359972646912"
model = "llama3.1"